# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaModelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=100)),
                ('mr_det_pos', models.CharField(max_length=100)),
                ('halflife', models.CharField(max_length=100)),
                ('hurstexponent', models.CharField(max_length=100)),
                ('adf', models.CharField(max_length=100)),
                ('ml_det_pos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrudeOilModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Log_Ret', models.FloatField()),
                ('Volatility', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataWareHouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_code', models.CharField(max_length=100)),
                ('Start', models.CharField(max_length=100)),
                ('End', models.CharField(max_length=100)),
                ('Lst_reg_dt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=100)),
                ('amean', models.FloatField()),
                ('hmean', models.FloatField()),
                ('gmean', models.FloatField()),
                ('median', models.FloatField()),
                ('mode', models.CharField(max_length=100)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('q1', models.FloatField()),
                ('q2', models.FloatField()),
                ('q3', models.FloatField()),
                ('var', models.FloatField()),
                ('std', models.FloatField()),
                ('cov', models.CharField(max_length=100)),
                ('corr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LinearGraphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_code', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Lst_reg_dt', models.CharField(max_length=100)),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Adj_Close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWeatherByCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('boston_temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('houston_temp', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioBuilderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_stationarity', models.CharField(max_length=100)),
                ('df_rank', models.CharField(max_length=100)),
                ('stationarity_codes', models.CharField(max_length=100)),
                ('df_machine_result', models.CharField(max_length=100)),
                ('df_machine_rank', models.CharField(max_length=100)),
                ('machine_codes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='', max_length=100)),
                ('train', models.CharField(default='', max_length=100)),
                ('test', models.CharField(default='', max_length=100)),
                ('split_ratio', models.FloatField(default=0.0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegressionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_code', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Lst_reg_dt', models.CharField(max_length=100)),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Adj_Close', models.FloatField()),
                ('Predicted_data', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='test1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname_text', models.CharField(max_length=200)),
            ],
        ),
    ]
