# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('possys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlphaModelModel',
        ),
        migrations.DeleteModel(
            name='CrudeOilModel',
        ),
        migrations.DeleteModel(
            name='DescriptiveModel',
        ),
        migrations.DeleteModel(
            name='LinearGraphModel',
        ),
        migrations.DeleteModel(
            name='MonthlyWeatherByCity',
        ),
        migrations.DeleteModel(
            name='PortfolioBuilderModel',
        ),
        migrations.DeleteModel(
            name='PreprocessorModel',
        ),
        migrations.DeleteModel(
            name='RegressionModel',
        ),
        migrations.DeleteModel(
            name='test1Model',
        ),
    ]
