# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possys', '0003_itemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_id', models.CharField(max_length=100)),
                ('In_out', models.CharField(max_length=100)),
                ('From_to', models.CharField(max_length=100)),
                ('Item_id', models.CharField(max_length=100)),
                ('Expense', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
            ],
        ),
    ]
