# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possys', '0006_auto_20170329_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemcategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemcategory_id', models.CharField(max_length=100)),
                ('Itemcategory_name', models.CharField(max_length=100)),
                ('Itemcategory_content', models.CharField(max_length=100)),
                ('Itemcategory_date', models.CharField(max_length=100)),
            ],
        ),
    ]
