# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possys', '0007_itemcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='Itemcategory_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
