# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_dailyweather_monthlyweatherbycity_monthlyweatherseattle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudeOilModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TimeField()),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Adj_Close', models.FloatField()),
                ('Log_Ret', models.FloatField()),
                ('Volatility', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DailyWeather',
        ),
        migrations.DeleteModel(
            name='MonthlyWeatherSeattle',
        ),
        migrations.RemoveField(
            model_name='monthlyweatherbycity',
            name='new_york_temp',
        ),
        migrations.RemoveField(
            model_name='monthlyweatherbycity',
            name='san_franciso_temp',
        ),
    ]
