# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_auto_20170107_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeoilmodel',
            name='Date',
            field=models.DateField(),
        ),
    ]
