# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_auto_20170107_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearGraphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_code', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Lst_reg_date', models.CharField(max_length=100)),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Adj_Close', models.FloatField()),
                ('Log_Ret', models.FloatField()),
                ('Volatility', models.FloatField()),
            ],
        ),
    ]
