# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_lineargraphmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineargraphmodel',
            old_name='Lst_reg_date',
            new_name='Lst_reg_dt',
        ),
        migrations.RemoveField(
            model_name='lineargraphmodel',
            name='Log_Ret',
        ),
        migrations.RemoveField(
            model_name='lineargraphmodel',
            name='Volatility',
        ),
    ]
