# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0007_regressionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressionmodel',
            name='Predicted_data',
            field=models.FloatField(default=0),
        ),
    ]
