# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_regressionmodel_predicted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regressionmodel',
            name='Predicted_data',
            field=models.FloatField(default=0),
        ),
    ]
