# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_auto_20170130_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWareHouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_code', models.CharField(max_length=100)),
                ('Start', models.CharField(max_length=100)),
                ('End', models.CharField(max_length=100)),
                ('Lst_reg_dt', models.CharField(max_length=100)),
            ],
        ),
    ]
