# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_datawarehousemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaModelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=100)),
                ('mr_det_pos', models.CharField(max_length=100)),
                ('halflife', models.CharField(max_length=100)),
                ('hurstexponent', models.CharField(max_length=100)),
                ('adf', models.CharField(max_length=100)),
                ('ml_det_pos', models.CharField(max_length=100)),
            ],
        ),
    ]
