# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0012_portfoliobuildermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('split_ratio', models.CharField(max_length=100)),
            ],
        ),
    ]
