# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0016_descriptivemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivemodel',
            name='mode',
            field=models.CharField(max_length=100),
        ),
    ]
