# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0017_auto_20170209_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivemodel',
            name='cov',
            field=models.CharField(max_length=100),
        ),
    ]
